### ISSUE TITLE
Non-fatal errors at exit of tests

### ISSUE THREAD

**Issue by felixonmars** [python-cmd2/cmd2#1113]
I'm not sure what caused these, although they are not fatal and not treated as errors to fail the tests:

```
======================= 928 passed, 2 skipped in 11.14s ========================
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "/build/python-cmd2/src/cmd2-2.0.0/cmd2/cmd2.py", line 4530, in _persist_history
    pickle.dump(self.history, fobj)
_pickle.PicklingError: Can't pickle <class 'cmd2.history.History'>: it's not the same object as cmd2.history.History
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "/build/python-cmd2/src/cmd2-2.0.0/cmd2/cmd2.py", line 4530, in _persist_history
    pickle.dump(self.history, fobj)
_pickle.PicklingError: Can't pickle <class 'cmd2.history.History'>: it's not the same object as cmd2.history.History
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "/build/python-cmd2/src/cmd2-2.0.0/cmd2/cmd2.py", line 4530, in _persist_history
    pickle.dump(self.history, fobj)
_pickle.PicklingError: Can't pickle <class 'cmd2.history.History'>: it's not the same object as cmd2.history.History
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "/build/python-cmd2/src/cmd2-2.0.0/cmd2/cmd2.py", line 4530, in _persist_history
    pickle.dump(self.history, fobj)
_pickle.PicklingError: Can't pickle <class 'cmd2.history.History'>: it's not the same object as cmd2.history.History
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "/build/python-cmd2/src/cmd2-2.0.0/cmd2/cmd2.py", line 4530, in _persist_history
    pickle.dump(self.history, fobj)
_pickle.PicklingError: Can't pickle <class 'cmd2.history.History'>: it's not the same object as cmd2.history.History
```

**Comment by kmvanbrunt** [comment]
The `cmd2.history.History` class changed between versions 1.5.0 and 2.0.0. Delete any persistent history files created with 1.5.0 and rerun the tests.

**Comment by tleonhardt** [comment]
@felixonmars can you please provide some more info to help reproduce?

Things like:
- What OS and version are you running tests on?
- What version of Python is it using?
- What terminal and shell?

**Comment by tleonhardt** [comment]
@kmvanbrunt We don't have anything in the CHANGELOG about the persistent history file format changing.  We should update that ASAP to make it clear this is backwards incompatible.

**Comment by kmvanbrunt** [comment]
@tleonhardt Done

**Comment by felixonmars** [comment]
> @felixonmars can you please provide some more info to help reproduce?
> 
> Things like:
> 
>     * What OS and version are you running tests on?
> 
>     * What version of Python is it using?
> 
>     * What terminal and shell?

Arch Linux x86_64 and Python 3.9.5, bash/konsole. The tests are running in a clean environment, from github tag tarballs, so I think no persistent history files are involved here.

**Comment by tleonhardt** [comment]
I tested on my Mac in a freshly built pipenv virtualenv and everything passes with latest master using these versions:
platform darwin -- Python 3.9.5, pytest-6.2.2, py-1.10.0, pluggy-0.13.1
plugins: cov-2.11.1, mock-3.5.1

**Comment by kmvanbrunt** [comment]
Does the Arch Linux environment have an older version of cmd2 installed?

**Comment by felixonmars** [comment]
No, but I think I find the difference. The errors are present when running the test suite with `python setup.py pytest`, but not present with a plain `pytest`.

There are other errors when invoking the test suite with plain `pytest` without cmd2 installed though, that's why we are using pytest-runner here.

**Comment by tleonhardt** [comment]
These errors appear to be related to the fact that we also run tests for a couple plugins as part of that extended suite.  PR #1114 is up to try to fix this.

**Comment by felixonmars** [comment]
I have tried to apply the change in #1114, but the errors are still present here.

**Comment by felixonmars** [comment]
It seems related to capsys failing to empty stderr from pytest if running with pytest-runner.

**Comment by tleonhardt** [comment]
PR #1115 modifies the manifest to exclude the `plugins` directory from a `cmd2` release tarball as published to PyPI.  A `cmd2` release should not include any plugins or tests for plugins.

**Comment by felixonmars** [comment]
I have tried to delete the whole plugins folder, but still getting the same (non-fatal) error. A specific test can trigger it here:

```
$ python setup.py pytest --addopts tests/test_history.py::test_persist_history_permission_error
...
1 passed in 1.30s
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "/home/felix/projects/arch/community/python-cmd2/trunk/src/cmd2-2.0.0/cmd2/cmd2.py", line 4531, in _persist_history
    pickle.dump(self.history, fobj)
_pickle.PicklingError: Can't pickle <class 'cmd2.history.History'>: it's not the same object as cmd2.history.History
$ pytest tests/test_history.py::test_persist_history_permission_error
...
1 passed in 1.30s
<no error>
```

**Comment by tleonhardt** [comment]
@felixonmars Please try deleting the `tests_isolated` folder and re-running tests

**Comment by felixonmars** [comment]
> @felixonmars Please try deleting the `tests_isolated` folder and re-running tests

I have tried, but unfortunately it's still the same :(

**Comment by tleonhardt** [comment]
@felixonmars We are not sure if it will fix your problem, but we just published a 2.0.1 release of `cmd2` to PyPI.

**Comment by felixonmars** [comment]
Thank you. I have tried to use the 2.0.1 PyPI tarball instead of the github tag tarball and the errors are still intact with pytest-runner (in a clean chroot).

**Comment by tleonhardt** [comment]
@felixonmars Ok, your last comment clued me onto something perhaps.  

The fix we put out in 2.0.1 will change what is in the PyPI tarball, but it will **not** change what is in the GitHub tarball.

GitHub just zips/tars up your source code exactly as it is on GitHub.  For the tarball published to PyPI, it is more nuanced.

**Comment by kmvanbrunt** [comment]
@felixonmars Is the Python module `cmd2-ext-test` installed in this environment? If so, what version is it?

**Comment by felixonmars** [comment]
> @felixonmars Is the Python module `cmd2-ext-test` installed in this environment? If so, what version is it?

It's not, as it's not present in the PyPI tarball at all now.

**Comment by tleonhardt** [comment]
@kmvanbrunt @anselor 

Any ideas on best path forward here?

I really don't like that `cmd2` now has unit/integration tests which rely on a plugin.  That feels like circular coupling to me.

**Comment by tleonhardt** [comment]
IMO we should either refactor the tests for Command Sets to not rely on the plugin or if this functionality in the plugin is so damn central we should just incorporate it into `cmd2`

**Comment by anselor** [comment]
The reason we require plugin tests as part of verifying cmd2 is because we want to verify that we don't break plugins again from API changes. The plugin tests are testing that plugins still work.

**Comment by anselor** [comment]
And obviously the problem is unrelated to the tests verifying plugins since you've removed them and the problem is still present.

**Comment by tleonhardt** [comment]
My understanding is the @felixonmars was pulling the tarball from GitHub, not PyPI which still contains all of the tests.

**Comment by felixonmars** [comment]
> My understanding is the @felixonmars was pulling the tarball from GitHub, not PyPI which still contains all of the tests.

I was, but I have also tried to use the PyPI tarball in a clean chroot, without cmd2 or any of the previously included test modules installed, and still able to reproduce this with pytest-runner.

**Comment by anselor** [comment]
It seems that the way a class gets imported can confuse pickle. The best guess right now is somehow the way pytest-runner is loading and running the tests changes the paths in some way that causes HistoryItem to be imported relative to a different path than normal execution.

We're looking into switching to JSON for persistence instead of pickle which is well known to be brittle and unreliable anyway.

**Comment by tleonhardt** [comment]
I think converting the persistent history to JSON is a good idea regardless, however if the problem is a path issue when using `pytest-runner` then that won't help.

**Comment by kmvanbrunt** [comment]
I was able to reproduce the error that @felixonmars was receiving using `pytest-runner`. Converting to JSON did fix the issue. `pickle` is the root cause of this since differences in how a module is imported can break it.

**Comment by kmvanbrunt** [comment]
@felixonmars I just released `cmd2` 2.1.0. Does the version fix the unit test bugs you were seeing?

**Comment by felixonmars** [comment]
Yes, all the errors are gone now. Thanks a lot :)
